### ISSUE TITLE
Can't access labs for AppU modules

### ISSUE THREAD

**Issue by RBAtkins0n** [appcelerator-training/LP-ASF#2]
## Expected behavior and actual behavior.
Was expecting to visit the learning labs online to learn more about module concepts, ended up on an issue reporter with no content in sight.

## Steps to reproduce the problem.
Link from AppU video for Alloy100 http://appcel.us/labs_alloy100 redirects to https://github.com/appcelerator-training/learning-modules-labs/tree/master/ALLOY100, which in turn references https://github.com/appcelerator-training/LP-ASF

## Specifications like the version of the project, operating system, or hardware.
Appcelerator backend 4.9.1

**Comment by Sophrinix** [comment]
I am a bit unclear on how you got the appcel.us/labs_alloy100 url to begin with.
What exact page is that link on?
Also, were you looking specifically for the labs or for a video?

**Comment by RBAtkins0n** [comment]
This link is on the AppU SDK fundamentals video "Alloy Overview", please see attached screenshot:
![screen shot 2017-01-23 at 10 22 57 pm](https://cloud.githubusercontent.com/assets/13369065/22226091/937cba0c-e1cd-11e6-8101-c0217ea9a8ee.png)

Please see the following excerpt as to why lab exercises are expected:

"Appcelerator Learning Paths

Learning Paths consist of bite-size modules you can tackle in the order and pace that works best for you. Each module includes course material, lab exercises and an assessment. Complete all modules in a learning path and receive a certification. New learning paths will continue to be added."

https://university.appcelerator.com/paths

**Comment by tzmartin** [comment]
The lab is located here: [https://s3.amazonaws.com/com.appc.lp-asf-labs/whrNirLMiW/README.html](https://s3.amazonaws.com/com.appc.lp-asf-labs/whrNirLMiW/README.html)

I will update the course repo with corresponding lab URLs.
